### ISSUE TITLE
Runtime Brute Force Attack / incorrect PIN (spoil inside ! ;)

### ISSUE THREAD

**Issue by ddouhine** [OWASP/iGoat-Swift#4]
The correct PIN seems to be:
<img width="643" alt="func_validatepin" src="https://user-images.githubusercontent.com/4519330/40551601-be28528a-603d-11e8-9941-b9b153c5cd4b.png">

Which is:
![image](https://user-images.githubusercontent.com/4519330/40551635-d39e403e-603d-11e8-997a-af339a0bdaec.png)

But it doesn't work.
![image](https://user-images.githubusercontent.com/4519330/40551840-54da3c0c-603e-11e8-8e37-ed517dbf3510.png)

Tested against the simulator and two real devices (jb and not jb).

Davy

**Comment by masbog** [comment]
Fixed.... wait for my PR.....

![image](https://user-images.githubusercontent.com/663374/40865422-5ecf88c2-6622-11e8-9617-5e3ac13f3273.png)

**Comment by swaroopsy** [comment]
This issue has been fixed. @ddouhine Let us know if any more issues. Thanks @masbog

**Comment by ddouhine** [comment]
Sorry guys, still not working for me using https://github.com/OWASP/iGoat-Swift/blob/master/iGoat-Swift_v1.0.ipa
Did the ipa had been packaged with the latest changes ?

![img_1272](https://user-images.githubusercontent.com/4519330/41539439-12f4b244-730e-11e8-9ccc-3486d40fa347.PNG)

**Comment by ddouhine** [comment]
Yes, the IPA needs to be updated ;)
I've just build the app using Xcode and "1181" works well ;)
Thanks guys !
